export const GET_USER_DATA = "GET_USER_DATA";
export const GET_LISTDATA_REQUEST = "GET_LISTDATA_REQUEST";
export const GET_LISTDATA_SUCCESS = "GET_LISTDATA_SUCCESS";
export const GET_LISTDATA_ERROR = "GET_LISTDATA_ERROR";